# Generated by Django 5.1.7 on 2025-04-02 07:46

from django.db import migrations

def convert_values(apps, schema_editor):
    TimeSlot = apps.get_model('admin_panel', 'TimeSlot')
    day_mapping = {
        'monday': 0,
        'tuesday': 1,
        'wednesday': 2,
        'thursday': 3,
        'friday': 4,
        'saturday': 5,
        'sunday': 6
    }
    
    time_mapping = {
        '09:00-10:00': 1,
        '10:00-11:00': 2,
        '11:00-12:00': 3,
        '12:00-13:00': 4,
        '14:00-15:00': 5,
        '15:00-16:00': 6,
        '16:00-17:00': 7
    }
    
    for timeslot in TimeSlot.objects.all():
        if isinstance(timeslot.day, str):
            timeslot.day = day_mapping.get(timeslot.day.lower(), 0)
        if isinstance(timeslot.time, str):
            timeslot.time = time_mapping.get(timeslot.time, 1)
        timeslot.save()

def reverse_convert_values(apps, schema_editor):
    TimeSlot = apps.get_model('admin_panel', 'TimeSlot')
    day_mapping = {
        0: 'monday',
        1: 'tuesday',
        2: 'wednesday',
        3: 'thursday',
        4: 'friday',
        5: 'saturday',
        6: 'sunday'
    }
    
    time_mapping = {
        1: '09:00-10:00',
        2: '10:00-11:00',
        3: '11:00-12:00',
        4: '12:00-13:00',
        5: '14:00-15:00',
        6: '15:00-16:00',
        7: '16:00-17:00'
    }
    
    for timeslot in TimeSlot.objects.all():
        if isinstance(timeslot.day, int):
            timeslot.day = day_mapping.get(timeslot.day, 'monday')
        if isinstance(timeslot.time, int):
            timeslot.time = time_mapping.get(timeslot.time, '09:00-10:00')
        timeslot.save()

class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_timeslot_is_active_alter_timeslot_day_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_values, reverse_convert_values),
    ]
