# Generated by Django 5.1.7 on 2025-04-02 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_convert_day_values"),
        ("student", "0003_alter_attendance_options_alter_marks_options_and_more"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "location",
                    models.CharField(default="Proctor Office", max_length=100),
                ),
                ("agenda", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_meetings",
                        to="teacher.teacher",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_meetings",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "time"],
            },
        ),
    ]
