# Generated by Django 5.1.7 on 2025-04-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_meeting"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineGeneratorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "students_per_slot",
                    models.IntegerField(
                        default=5, help_text="Maximum number of students per time slot"
                    ),
                ),
                (
                    "min_slots_per_teacher",
                    models.IntegerField(
                        default=2,
                        help_text="Minimum number of slots each teacher should have",
                    ),
                ),
                (
                    "max_slots_per_teacher",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum number of slots each teacher can have",
                    ),
                ),
                (
                    "preferred_days",
                    models.JSONField(
                        default=list,
                        help_text="List of preferred days for scheduling (0-6, where 0 is Monday)",
                    ),
                ),
                (
                    "preferred_times",
                    models.JSONField(
                        default=list,
                        help_text="List of preferred time slots for scheduling (1-7)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher_constraints",
                    models.JSONField(
                        default=dict,
                        help_text="Constraints for specific teachers (e.g., {'teacher_id': {'preferred_days': [0,1,2], 'preferred_times': [1,2,3]}})",
                    ),
                ),
                (
                    "student_constraints",
                    models.JSONField(
                        default=dict,
                        help_text="Constraints for specific students (e.g., {'student_id': {'preferred_days': [0,1,2], 'preferred_times': [1,2,3]}})",
                    ),
                ),
                (
                    "avoid_conflicts",
                    models.BooleanField(
                        default=True,
                        help_text="Avoid scheduling conflicts for teachers and students",
                    ),
                ),
                (
                    "balance_load",
                    models.BooleanField(
                        default=True, help_text="Balance the load among teachers"
                    ),
                ),
                (
                    "use_existing_proctors",
                    models.BooleanField(
                        default=True,
                        help_text="Use existing proctor assignments when generating routine",
                    ),
                ),
                (
                    "allow_proctor_changes",
                    models.BooleanField(
                        default=False,
                        help_text="Allow changes to existing proctor assignments",
                    ),
                ),
                (
                    "semester_filter",
                    models.JSONField(
                        default=list,
                        help_text="List of semesters to include in routine generation",
                    ),
                ),
                (
                    "group_by_semester",
                    models.BooleanField(
                        default=False,
                        help_text="Group students by semester when generating routine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routine Generator Settings",
                "verbose_name_plural": "Routine Generator Settings",
            },
        ),
        migrations.DeleteModel(
            name="Meeting",
        ),
    ]
