# Generated by Django 4.2.17 on 2025-04-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_routinegeneratorsettings_delete_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
