# Generated by Django 5.1.7 on 2025-04-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_address_alter_user_phone_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
