# Generated by Django 5.1.7 on 2025-04-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_meeting"),
        ("proctor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proctormeeting",
            options={"ordering": ["date"]},
        ),
        migrations.AlterUniqueTogether(
            name="proctormeeting",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="proctormeeting",
            name="time_slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="admin_panel.timeslot",
            ),
        ),
        migrations.RemoveField(
            model_name="proctormeeting",
            name="time",
        ),
    ]
