# Generated by Django 5.1.7 on 2025-04-03 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctor", "0002_alter_proctormeeting_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proctormeeting",
            options={"ordering": ["date", "time"]},
        ),
        migrations.AddField(
            model_name="proctormeeting",
            name="time",
            field=models.TimeField(blank=True, default="09:00:00", null=True),
        ),
        migrations.CreateModel(
            name="Proctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("office_location", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="proctormeeting",
            name="proctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="proctor.proctor"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="proctormeeting",
            unique_together={("proctor", "date", "time")},
        ),
        migrations.RemoveField(
            model_name="proctormeeting",
            name="time_slot",
        ),
    ]
