# Generated by Django 5.1.7 on 2025-04-08 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proctor", "0003_alter_proctormeeting_options_proctormeeting_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_text", models.TextField()),
                ("action_items", models.TextField(blank=True, null=True)),
                ("next_meeting_suggestions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="proctor.proctormeeting",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Meeting Summaries",
            },
        ),
    ]
